services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
  mysql:
    image: mysql:8.0.37
    container_name: mysql
    restart: always
    env_file:
      - .env
  
  mongo:
    image: mongo:5.0.14
    container_name: mongo
    restart: always

networks:
  default:
    name: docker-network
    external: true