services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: proxy_server
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d

networks:
  default:
    name: development
    external: true