services:
  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    environment:
        CERTBOT_EMAIL: gabrielqwes123@gmail.com
        ENVSUBST_VARS: FQDN
        FQDN: ${CERTBOT_DOMAIN}

  mysql:
    image: mysql:8.0.37
    container_name: mysql
    restart: always
    env_file:
      - .env
  
  mongo:
    image: mongo:5.0.14
    container_name: mongo
    restart: always

networks:
  default:
    name: docker-network
    external: true

volumes:
    letsencrypt: