name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
  install-runner:
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H server_ip >> ~/.ssh/known_hosts

      - name: Deploy
        run: ssh {{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} 'ls'