name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: ls
      - name: Deploy
        run: pwd